version: "2.3"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=s3,dynamodb,sqs,iam,ssm,firehose
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./scripts/localstack:/docker-entrypoint-initaws.d
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal dynamodb list-tables
          && awslocal s3 ls
          && awslocal sqs list-queues
      interval: 5s
      timeout: 10s
      start_period: 30s

  pizza-ordering-server:
    container_name: pizza-ordering-server
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file:
      - ./.env.example
    ports:
      - "3000:3000"
    entrypoint: npm run start:server
    volumes:
    - .:/app
    - /app/node_modules
    depends_on:
      localstack:
        condition: service_healthy

  pizza-ordering-worker:
    container_name: pizza-ordering-worker
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file:
      - ./.env.example
    entrypoint: npm run start:worker
    volumes:
    - .:/app
    - /app/node_modules
    depends_on:
      localstack:
        condition: service_healthy
